# Generated by Django 5.0.3 on 2024-04-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
    ]
