# Generated by Django 5.0.3 on 2024-04-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_image_url_category_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
    ]
