# Generated by Django 5.0.3 on 2024-03-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('available_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spaces_booked', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='activities.activity')),
            ],
        ),
    ]
